batch_size = 64
model_name = "nishimoto/contriever-sentencetransformer"
dataset_name = "trec-covid"
result_output_dir = "./outputs/truncation_beir_eval/"
cache_dir = "./cache/truncation_beir_eval/contriever-sentencetransformer/trec-covid"
