batch_size = 64
model_name = "sentence-transformers/paraphrase-MiniLM-L3-v2"
dataset_name = "scidocs"
result_output_dir = "./outputs/truncation_beir_eval/"
cache_dir = "./cache/truncation_beir_eval/paraphrase-MiniLM-L3-v2/sscidocs"
