batch_size = 64
model_name = "nishimoto/contriever-sentencetransformer"
dataset_name = "quora"
result_output_dir = "./outputs/random_truncation_beir_eval/"
cache_dir = "./cache/truncation_beir_eval/contriever-sentencetransformer/quora"
