batch_size = 4
model_name = "intfloat/e5-mistral-7b-instruct"
dataset_name = "dbpedia-entity"
result_output_dir = "./outputs/random_truncation_nanobeir_eval/"
cache_dir = "./cache/truncation_beir_eval/e5-mistral-7b-instruct/dbpedia-entity"
