batch_size = 64
model_name = "nishimoto/contriever-sentencetransformer"
result_output_dir = "./outputs/truncation_mteb_eval/"
cache_dir = "./cache/truncation_mteb_eval/contriever-sentencetransformer"
