batch_size = 64
model_name = "sentence-transformers/sentence-t5-base"
dataset_name = "fever"
result_output_dir = "./outputs/random_truncation_beir_eval/"
cache_dir = "./cache/random_truncation_beir_eval/sentence-t5-base/fever"
