batch_size = 64
model_name = "sentence-transformers/sentence-t5-base"
dataset_name = "trec-covid"
result_output_dir = "./outputs/random_truncation_beir_eval/"
cache_dir = "./cache/truncation_beir_eval/sentence-t5-base/trec-covid"
