batch_size = 64
model_name = "sentence-transformers/paraphrase-MiniLM-L3-v2"
dataset_name = "hotpotqa"
result_output_dir = "./outputs/random_truncation_beir_eval/"
cache_dir = "./cache/random_truncation_beir_eval/paraphrase-MiniLM-L3-v2/hotpotqa"
