batch_size = 64
model_name = "intfloat/e5-large-v2"
dataset_name = "webis-touche2020"
result_output_dir = "./outputs/truncation_beir_eval/"
cache_dir = "./cache/truncation_beir_eval/e5-large-v2/webis-touche2020"
