batch_size = 64
model_name = "intfloat/e5-large-v2"
dataset_name = "scifact"
result_output_dir = "./outputs/random_truncation_beir_eval_e5-large/"
cache_dir = "./cache/truncation_beir_eval/e5-large-v2/scifact"
