batch_size = 64
model_name = "sentence-transformers/all-mpnet-base-v2"
dataset_name = "nq"
result_output_dir = "./outputs/random_truncation_beir_eval/"
cache_dir = "./cache/truncation_beir_eval/all-mpnet-base-v2/nq"
